server:
  port: 8080

spring:
  application:
    name: hjj-data-tool
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:/mappers/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
